### PR TITLE
fix linting

### PR DESCRIPTION
**Pull request by fzyyy0601**
Update routes.py, test_routes.py, helpers.py, models.py, test_models.py to fix linting issues. Code rated ad 10.00/10

### CODE REVIEW

**Comment by loixe** [comment]
When can we merge this, now or after 'change end date'?

**Comment by tanaytrivedi** [comment]
I think this should be the last merge of the sprint.

**Comment by bkudler** [comment]
> I think this should be the last merge of the sprint.

This shouldn't and can't be the last merge of the sprint. The CI cannot be merged until the linting is fixed, because all PRs will fail the CI linting step. This needs to be merged BEFORE the change_end_date, then change_end_date needs to be updated to have 10/10 linting. Ideally, it should be linting, and then it doesn't matter what gets merged after that. However, I think it makes the most sense to do linting, CI, then end_date

**Review by bkudler — APPROVED** [review]
Looks great!

**Pull request merged**
